name: Style-Swap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - CogSci
  - defaults
dependencies:
  - aom=3.9.1
  - av=12.3.0
  - blas=2.112
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cairo=1.18.0
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - cuda-cccl=12.5.39
  - cuda-cccl_win-64=12.5.39
  - cuda-cudart=11.8.89
  - cuda-cudart-dev=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-libraries-dev=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvrtc-dev=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-profiler-api=12.5.39
  - cuda-runtime=11.8.0
  - cuda-version=12.5
  - dav1d=1.2.1
  - expat=2.6.2
  - ffmpeg=6.1.1
  - filelock=3.15.4
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - graphite2=1.3.13
  - gxx_linux-64
  - h2=4.1.0
  - harfbuzz=9.0.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - jinja2=3.1.4
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcublas-dev=11.11.3.6
  - libcufft=10.9.0.58
  - libcufft-dev=10.9.0.58
  - libcurand=10.3.6.82
  - libcurand-dev=10.3.6.82
  - libcusolver=11.4.1.48
  - libcusolver-dev=11.4.1.48
  - libcusparse=11.7.5.86
  - libcusparse-dev=11.7.5.86
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libglib=2.80.3
  - libhwloc=2.11.1
  - libiconv=1.17
  # - libintl=0.22.5
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnpp-dev=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libnvjpeg-dev=11.9.0.86
  - libopus=1.3.1
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libuv=1.48.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzlib=1.3.1
  # - m2w64-gcc-libgfortran=5.3.0
  # - m2w64-gcc-libs=5.3.0
  # - m2w64-gcc-libs-core=5.3.0
  # - m2w64-gmp=6.1.0
  # - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=2.1.5
  - mkl-devel=2021.4.0
  - mkl-include=2021.4.0
  - mpmath=1.3.0
  # - msys2-conda-epoch=20160418
  - networkx=3.3
  - ninja=1.12.1
  - numpy=1.26.4
  - openh264=2.4.1
  - openjpeg=2.5.2
  - openssl=3.3.1
  - pcre2=10.44
  - pillow=10.4.0
  - pip=24.0
  # - pixman=0.43.4
  - pthread-stubs=0.4
  # - pthreads-win32=2.9.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - pytorch=2.3.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - requests=2.32.3
  - scipy=1.14.0
  - setuptools=71.0.4
  - svt-av1=2.1.2
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2024a
  # - ucrt=10.0.22621.0
  - urllib3=2.2.2
  # - vc=14.3
  # - vc14_runtime=14.40.33810
  # - vs2015_runtime=14.40.33810
  - wheel=0.43.0
  # - win_inet_pton=1.1.0
  - x264=1!164.3095
  - x265=3.5
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - PyOpenGL
      - streamlit
      - absl-py==2.1.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - black==24.4.2
      - click==8.1.7
      - git+https://github.com/openai/CLIP.git
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - decorator==5.1.1
      - git+https://github.com/facebookresearch/detectron2.git
      - exceptiongroup==1.2.2
      - executing==2.0.1
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - ftfy==6.2.0
      - fvcore==0.1.5.post20221221
      - grpcio==1.65.1
      - hydra-core==1.3.2
      - intel-openmp==2021.4.0
      - iopath==0.1.9
      - ipython==8.26.0
      - jedi==0.19.1
      - kiwisolver==1.4.5
      - markdown==3.6
      - matplotlib==3.9.1
      - matplotlib-inline==0.1.7
      - mkl==2021.4.0
      - mypy-extensions==1.0.0
      - omegaconf==2.3.0
      - opencv-python==4.10.0.84
      - packaging==24.1
      - parso==0.8.4
      - pathspec==0.12.
